# Generated by Django 3.1.1 on 2020-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bar_value', models.IntegerField()),
                ('d_allocated', models.IntegerField()),
                ('d_available', models.IntegerField()),
                ('f_paid', models.IntegerField()),
                ('f_open', models.IntegerField()),
            ],
        ),
    ]
